### ISSUE TITLE
Indeterminate results on coveralls.io

### ISSUE THREAD

**Issue by aggieben** [mattn/goveralls#27] opened 2014-03-11 19:21 UTC
After getting a build set up on Travis-CI (see my [.travis.yml](https://github.com/aggieben/trello/blob/master/.travis.yml)), I finally got `goveralls` working (seemingly), but the results posted to coveralls.io seem very incomplete.  Here is my most recent Travis-CI log: https://travis-ci.org/aggieben/trello/jobs/20551786#L90, which indicates the coverage job: https://coveralls.io/jobs/1381003.

Screenshots:
![image](https://f.cloud.github.com/assets/1321/2389841/8f6759c4-a952-11e3-9873-00186c9bca8e.png)

![image](https://f.cloud.github.com/assets/1321/2389847/9c7d0848-a952-11e3-97b8-9cf7e48b0c0e.png)

The coverage job not only doesn't indicate any coverage stats (although otherwise appears to be valid), but it doesn't show up in my dashboard at all.  

What's going on here?

**Comment by mattn** [comment] 2017-03-10 03:21
do you still have this issue?

**Comment by aggieben** [comment] 2017-03-10 04:05
Oh man, I haven't looked at this probably in two years, so I have no idea.

**Comment by crazcalm** [comment] 2018-06-26 17:18
I have this issue, but it does not happen to all the packages in my repo.

![cover_issue2](https://user-images.githubusercontent.com/3482344/41928414-1de98914-7943-11e8-8f74-57b944724270.png)

![cover_issue](https://user-images.githubusercontent.com/3482344/41928423-25572e9a-7943-11e8-803f-548aad0eaaaf.png)

![cover_issue3](https://user-images.githubusercontent.com/3482344/41928430-2b253ede-7943-11e8-9752-47c933de50b4.png)

As you can see, the file package is not covered at all in the dashboard, but the database package is.

**Comment by crazcalm** [comment] 2018-06-27 20:12
I found a work around. If I use https://github.com/go-playground/overalls to create the coverage report, and then use goveralls to send that report to coveralls, then everything works out fine. For more details on this work around, check out the overalls repo.

**Comment by gdm85** [comment] 2020-10-30 16:45
I am closing this; if the issue is still present we can reopen this or create a new issue and go through some troubleshooting steps.

**Closed by gdm85** 2020-10-30 16:45 UTC
