### ISSUE TITLE
Can't restart travis-ci job

### ISSUE THREAD

**Issue by nunnatsa** [mattn/goveralls#171] opened 2020-06-04 08:47 UTC
When trying to re-run a travis job, it never succeed and reports the following error:

```
$ $GOPATH/bin/goveralls -service=travis-ci -coverprofile=#####
Bad response status from coveralls: 422
{"message":"service_job_id (####) must be unique for Travis Jobs not supplying a Coveralls Repo Token","error":true}
The command "$GOPATH/bin/goveralls -service=travis-ci -coverprofile=######.coverprofile" exited with 1.
```

**Comment by gdm85** [comment] 2020-10-30 16:03
Have you set `COVERALLS_SERVICE_JOB_ID` or `TRAVIS_JOB_ID`?

**Comment by nbaztec** [comment] 2020-11-02 13:07
If the travis job id doesn't change on re-run (which I think it doesn't), this can definitely cause this error on coveralls side, since the `job_id` needs to be unique per push or omitted. @gdm85 I think we need a mitigation strategy for this scenario in general.

**Comment by gdm85** [comment] 2020-11-02 20:33
What does coveralls.io suggest to do in this case? Travis CI is officially supported by them.

**Comment by nbaztec** [comment] 2020-11-02 21:48
Seems to be an issue on [coveralls'](https://github.com/lemurheavy/coveralls-public/issues/1264#issuecomment-465257524) side.

Can be closed.

**Comment by gdm85** [comment] 2020-11-03 07:16
Let's close it until it can be reproduced again and with a better context.

**Closed by gdm85** 2020-11-03 07:16 UTC
Labels: needs-triage
