### ISSUE TITLE
coveralls with github actions

### ISSUE THREAD

**Issue by umputun** [mattn/goveralls#143] opened 2019-11-01 18:01 UTC
I have tried to integrate coveralls into github actions and run into several issues:

- Actions support is not documented anywhere. It is unclear what `-service` to pass if any
- I think the proper setup requires the user to export  `GIT_BRANCH` and (maybe) `GIT_TAG`. Without it, goveralls thinks the build was for a detached head
```
export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
export GIT_TAG="${GITHUB_REF/refs\/tags\//}"
if [[ "$GIT_TAG" != "$GITHUB_REF" ]]; then
   export GIT_BRANCH=$GIT_TAG
fi
```
- Long Ids from actions (i.e. `DFF1E976041AF8B5B09349FABC9882E9E5B813D1`) are too long and goveralls doesn't show them nice on some resolutions . Maybe we can just take a substring short enough to make it nicer looking but long to be unique enough?

**Comment by mattn** [comment] 2019-11-01 18:04
@jderusse can you handle something for this?

**Comment by jderusse** [comment] 2019-11-01 20:30
> Actions support is not documented anywhere. It is unclear what -service to pass if any

list of services is documented in coveralls: https://coveralls.io/supported-continuous-integration
Given GithubAction is not managed yed, just don't use this parameter.

> I think the proper setup requires the user to export GIT_BRANCH and (maybe) GIT_TAG. Without it, goveralls thinks the build was for a detached head

I'm able to reproduce it and send a patch...

> Long Ids from actions (i.e. DFF1E976041AF8B5B09349FABC9882E9E5B813D1) are too long and goveralls doesn't show them nice on some resolutions . Maybe we can just take a substring short enough to make it nicer looking but long to be unique enough?

I noticed that too and agreed. I suggest to set the JobID to an empty string and let coveralls  use a autoincrement id. What do you think @mattn ? I'm not sure to understand the purpose of this ID.

**Comment by umputun** [comment] 2019-11-01 20:34
> list of services is documented in coveralls: https://coveralls.io/supported-continuous-integration

I think this is `GitHub Action` (i.e. -service="GitHub Action"). Don't recall the source but most likely found it in coveralls actions code

**Comment by umputun** [comment] 2019-11-01 20:39
>  I suggest to set the JobID to an empty string and let coveralls use a autoincrement id.

I can be wrong, but I think coveralls using id to match & update coverage for the build. Making it automatic can be troublesome as some failed (on github side) builds may send coverage before they fail. However, github actions allow restarting such build manually and it may lead to duplicated reports on coveralls side.

**Comment by jderusse** [comment] 2019-11-01 20:44
The official coveralls github actions uses:
- service="github" https://github.com/coverallsapp/github-action/blob/master/src/run.ts#L24
- job=sha (as does goveralls) https://github.com/coverallsapp/github-action/blob/master/src/run.ts#L42

**Comment by jderusse** [comment] 2019-11-01 21:04
just tried with "service=github" and got `{"message":"Couldn't find a repository matching this job.","error":true}`

**Comment by umputun** [comment] 2019-11-01 21:21
mine with ` -service="GitHub Action"` https://coveralls.io/github/umputun/remark?branch=master

Not sure if coveralls do anything special in this case, but at least not rejected

**Comment by theory** [comment] 2019-12-01 14:48
For me, neither [`-service=github`](/iovation/flockd/commit/fba86d6b77423c89d3deac9e21565a0ea2f77b95/checks?check_suite_id=336137322) nor [`-service="GitHub Action"`](/iovation/flockd/commit/82ffa7832673de705bd07fa62d069da28709a16e/checks?check_suite_id=336494042) work. :-(

**Comment by jderusse** [comment] 2019-12-01 15:21
it depends of the value of `COVERALLS_TOKEN`.
see https://github.com/mattn/goveralls/pull/144#discussion_r342997287

**Comment by theory** [comment] 2019-12-01 16:19
Sorry to be dense, but I tried using the token at the top of the coveralls repo page, which looks like this:

<img width="218" alt="Screen Shot 2019-12-01 at 11 14 22 AM" src="https://user-images.githubusercontent.com/46604/69916671-d94be380-142b-11ea-9d7e-ee034dc4753a.png">

And that [did not work](/iovation/flockd/commit/a534de73a1563fa8b3cfa3cab11d75dc4a53af3c/checks?check_suite_id=336130970). But I'm pretty confused, because in the README and in [#144 (comment)](https://github.com/mattn/goveralls/pull/144#discussion_r342997287) it's called a "GitHub token" and is at the " bottom of your repository's page when you are logged in to Coveralls.io." Is it supposed to be at the bottom of the coveralls repo page? And is it a GItHub token or a Coveralls token?

**Comment by theory** [comment] 2019-12-01 16:25
Ah, maybe it's just something that's magically there, always in `${{ secrets.GITHUB_TOKEN }}`. Because that gets me [a bit further](/iovation/flockd/runs/328031756).

**Comment by theory** [comment] 2019-12-01 18:44
And got past that by testing only 1.11 or later. 🤷‍♂

**Comment by shogo82148** [comment] 2020-01-13 08:13
You need to set GOPATH correctly.

https://github.com/mattn/goveralls/pull/161 https://github.com/mattn/goveralls#test-with-legacy-gopath-mode

**Comment by wenbenz** [comment] 2020-04-26 20:31
Not sure if this is the right place to put this, but I'm getting
```
Run GO111MODULE=off go get github.com/mattn/goveralls
  GO111MODULE=off go get github.com/mattn/goveralls
  $(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  shell: /bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.14.2/x64
    COVERALLS_TOKEN: ***
20:23:39 gocover.go:90: Can't find can't find "Errors.go": import "/home/runner/work/sago/sago/": cannot import absolute path
##[error]Process completed with exit code 1.
```
whenever I try to run the workflow. Has anyone else seen this?

**Comment by nbaztec** [comment] 2020-11-02 10:30
@theory If the issue has be resolved for you, can the issue be closed?

**Comment by theory** [comment] 2020-11-02 16:19
Yes, it is resolved for me, though I can't speak for the other folks on this ticket.

**Comment by nbaztec** [comment] 2020-11-02 17:06
@umputun could you verify if the solutions worked for you, please?

**Comment by umputun** [comment] 2020-11-02 17:12
for me, it works fine with `-service="github"` and `COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

**Comment by nbaztec** [comment] 2020-11-02 17:13
Thanks for confirming!

Closing this issue.

**Closed by nbaztec** 2020-11-02 17:13 UTC
